import type { Metadata } from "next";
import { Header } from "./components/layout";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body className="page-container">
        <AppProvider>
          <>
            <Header />
            {children}
          </>
        </AppProvider>
      </body>
    </html>
  );
}
